GAME_DATE = 10
GAME_TIME = 11
GAME_LOCATION = 12
GAME_OPPONENT = 13
GAME_ARRIVAL = 14
GAME_TEAM = 15
GAME_DELETE_CONFIRM = 20
EDIT_GAME_SELECT = 30
EDIT_GAME_FIELD = 31
EDIT_GAME_NEW_VALUE = 32
GAMES_FILE = "games_data"

